import type { Metadata } from "next";
import { Geologica, Inter, Montserrat } from "next/font/google";
import "./globals.css";
import { Header } from "@/widgets/header";
import React from "react";
import { ThemeProvider } from "@/app/providers";

const montserrat = Montserrat({ subsets: ["latin"] });
const geologica = Geologica({ subsets: ["latin"] });
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={geologica.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
